var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),h=(a,b)=>{throw b;},ba="object"==typeof window,l="function"==typeof importScripts,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,t="",da,u,v;
if(ca){var fs=require("fs"),ea=require("path");t=l?ea.dirname(t)+"/":__dirname+"/";da=(a,b)=>{a=a.startsWith("file://")?new URL(a):ea.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=da(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ea.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof w||a.context instanceof w))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});h=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(ba||l)l?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),t=0!==t.indexOf("blob:")?t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var fa=f.print||console.log.bind(console),x=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.quit&&(h=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&z("no native wasm support detected");var ha,ia=!1,A,ja,ka,B,C,D,E,F,la=[],ma=[],na=[],oa=[],pa=[];function qa(){var a=f.preRun.shift();la.unshift(a)}var G=0,ra=null,H=null;function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";x(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function sa(a){return a.startsWith("data:application/octet-stream;base64,")}var I;I="index.wasm";
if(!sa(I)){var ta=I;I=f.locateFile?f.locateFile(ta,t):t+ta}function ua(a){try{if(a==I&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function va(a){if(!y&&(ba||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ua(a));if(u)return new Promise((b,c)=>{u(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>ua(a))}function wa(a,b,c){return va(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{x("failed to asynchronously prepare wasm: "+d);z(d)})}
function xa(a,b){var c=I;y||"function"!=typeof WebAssembly.instantiateStreaming||sa(c)||c.startsWith("file://")||ca||"function"!=typeof fetch?wa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){x("wasm streaming compile failed: "+e);x("falling back to ArrayBuffer instantiation");return wa(c,a,b)}))}function w(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
function ya(a){for(;0<a.length;)a.shift()(f)}var za="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Aa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&za)return za.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function J(a,b){return a?Aa(A,a,b):""}
function Ba(a){var b=Ca();a();Da(b)}var Ea=0;function Fa(){for(var a=K.length-1;0<=a;--a)Ga(a);K=[];Ha=[]}var Ha=[];function Ia(){if(Ea&&Ja.Vb)for(var a=0;a<Ha.length;++a){var b=Ha[a];Ha.splice(a,1);--a;b.Ec.apply(null,b.uc)}}var K=[];function Ga(a){var b=K[a];b.target.removeEventListener(b.Ob,b.pc,b.Pb);K.splice(a,1)}
function L(a){function b(d){++Ea;Ja=a;Ia();a.Rb(d);Ia();--Ea}if(!a.target)return-4;if(a.Qb)a.pc=b,a.target.addEventListener(a.Ob,b,a.Pb),K.push(a),Ka||(oa.push(Fa),Ka=!0);else for(var c=0;c<K.length;++c)K[c].target==a.target&&K[c].Ob==a.Ob&&Ga(c--);return 0}function La(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ka,Ja,Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function N(a){a=2<a?J(a):a;return Ta[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Ua(a){return 0>Ta.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}ca&&(global.performance=require("perf_hooks").performance);
function O(a,b,c){var d=A;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var m=a.charCodeAt(++k);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e}
function Va(a,b,c,d,e,k){Ma||(Ma=P(256));a={target:N(a),Ob:k,Qb:d,Rb:function(g=event){var m=g.target.id?g.target.id:"",n=Ma;O(La(g.target),n+0,128);O(m,n+128,128);F.get(d)(e,n,b)&&g.preventDefault()},Pb:c};return L(a)}
function Wa(a,b,c,d,e,k){Na||(Na=P(176));a={target:N(a),Vb:!0,Ob:k,Qb:d,Rb:function(g){var m=Na;E[m>>3]=g.timeStamp;var n=m>>2;B[n+2]=g.location;B[n+3]=g.ctrlKey;B[n+4]=g.shiftKey;B[n+5]=g.altKey;B[n+6]=g.metaKey;B[n+7]=g.repeat;B[n+8]=g.charCode;B[n+9]=g.keyCode;B[n+10]=g.which;O(g.key||"",m+44,32);O(g.code||"",m+76,32);O(g.char||"",m+108,32);O(g.locale||"",m+140,32);F.get(d)(e,m,b)&&g.preventDefault()},Pb:c};return L(a)}
function Xa(a,b,c){E[a>>3]=b.timeStamp;a>>=2;B[a+2]=b.screenX;B[a+3]=b.screenY;B[a+4]=b.clientX;B[a+5]=b.clientY;B[a+6]=b.ctrlKey;B[a+7]=b.shiftKey;B[a+8]=b.altKey;B[a+9]=b.metaKey;ja[2*a+20]=b.button;ja[2*a+21]=b.buttons;B[a+11]=b.movementX;B[a+12]=b.movementY;c=Ua(c);B[a+13]=b.clientX-c.left;B[a+14]=b.clientY-c.top}
function Q(a,b,c,d,e,k){Oa||(Oa=P(72));a=N(a);return L({target:a,Vb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Ob:k,Qb:d,Rb:function(g=event){Xa(Oa,g,a);F.get(d)(e,Oa,b)&&g.preventDefault()},Pb:c})}function Ya(a,b,c,d,e){Pa||(Pa=P(260));return L({target:a,Ob:e,Qb:d,Rb:function(k=event){var g=Pa,m=document.pointerLockElement||document.Sb||document.bc||document.ac;B[g>>2]=!!m;var n=m&&m.id?m.id:"";O(La(m),g+4,128);O(n,g+132,128);F.get(d)(20,g,b)&&k.preventDefault()},Pb:c})}
function Za(a,b,c,d,e){return L({target:a,Ob:e,Qb:d,Rb:function(k=event){F.get(d)(38,0,b)&&k.preventDefault()},Pb:c})}
function $a(a,b,c,d){Qa||(Qa=P(36));a=N(a);return L({target:a,Ob:"resize",Qb:d,Rb:function(e=event){if(e.target==a){var k=document.body;if(k){var g=Qa;B[g>>2]=e.detail;B[g+4>>2]=k.clientWidth;B[g+8>>2]=k.clientHeight;B[g+12>>2]=innerWidth;B[g+16>>2]=innerHeight;B[g+20>>2]=outerWidth;B[g+24>>2]=outerHeight;B[g+28>>2]=pageXOffset;B[g+32>>2]=pageYOffset;F.get(d)(10,g,b)&&e.preventDefault()}}},Pb:c})}
function ab(a,b,c,d,e,k){Ra||(Ra=P(1696));a=N(a);return L({target:a,Vb:"touchstart"==k||"touchend"==k,Ob:k,Qb:d,Rb:function(g){for(var m,n={},r=g.touches,q=0;q<r.length;++q)m=r[q],m.dc=m.ec=0,n[m.identifier]=m;for(q=0;q<g.changedTouches.length;++q)m=g.changedTouches[q],m.dc=1,n[m.identifier]=m;for(q=0;q<g.targetTouches.length;++q)n[g.targetTouches[q].identifier].ec=1;r=Ra;E[r>>3]=g.timeStamp;var p=r>>2;B[p+3]=g.ctrlKey;B[p+4]=g.shiftKey;B[p+5]=g.altKey;B[p+6]=g.metaKey;p+=7;var M=Ua(a),U=0;for(q in n)if(m=
n[q],B[p]=m.identifier,B[p+1]=m.screenX,B[p+2]=m.screenY,B[p+3]=m.clientX,B[p+4]=m.clientY,B[p+5]=m.pageX,B[p+6]=m.pageY,B[p+7]=m.dc,B[p+8]=m.ec,B[p+9]=m.clientX-M.left,B[p+10]=m.clientY-M.top,p+=13,31<++U)break;B[r+8>>2]=U;F.get(d)(e,r,b)&&g.preventDefault()},Pb:c})}
function bb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,k){b.drawArraysInstancedANGLE(c,d,e,k)},a.drawElementsInstanced=function(c,d,e,k,g){b.drawElementsInstancedANGLE(c,d,e,k,g)})}
function cb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function db(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function eb(a){a.zc=a.getExtension("WEBGL_multi_draw")}
var fb=1,gb=[],R=[],hb=[],ib=[],jb=[],S=[],kb=[],lb={},mb=4;function T(a){nb||(nb=a)}function ob(a){for(var b=fb++,c=a.length;c<b;c++)a[c]=null;return b}function pb(a,b){a.Sb||(a.Sb=a.getContext,a.getContext=function(d,e){e=a.Sb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?qb(c,b):0}function qb(a,b){var c=ob(kb),d={xc:c,attributes:b,version:b.sc,Zb:a};a.canvas&&(a.canvas.tc=d);kb[c]=d;("undefined"==typeof b.cc||b.cc)&&rb(d);return c}
function rb(a){a||(a=sb);if(!a.rc){a.rc=!0;var b=a.Zb;bb(b);cb(b);db(b);b.wc=b.getExtension("EXT_disjoint_timer_query");eb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var nb,sb;function tb(a,b,c,d,e,k){a={target:N(a),Ob:k,Qb:d,Rb:(g=event)=>{F.get(d)(e,0,b)&&g.preventDefault()},Pb:c};L(a)}
function ub(a,b,c,d){Sa||(Sa=P(104));return L({target:a,Vb:!0,Ob:"wheel",Qb:d,Rb:function(e=event){var k=Sa;Xa(k,e,a);E[k+72>>3]=e.deltaX;E[k+80>>3]=e.deltaY;E[k+88>>3]=e.deltaZ;B[k+96>>2]=e.deltaMode;F.get(d)(9,k,b)&&e.preventDefault()},Pb:c})}var vb=["default","low-power","high-performance"],wb=[null,[],[]];function xb(a,b,c,d){for(var e=0;e<a;e++){var k=V[c](),g=k&&ob(d);k?(k.name=g,d[g]=k):T(1282);B[b+4*e>>2]=g}}
function yb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:T(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)B[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:T(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}B[b>>2]=c}else T(1281)}
function zb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function Ab(a){var b=zb(a)+1,c=P(b);c&&O(a,c,b);return c}function Bb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function W(a){var b=V.oc;if(b){var c=b.Ub[a];"number"==typeof c&&(b.Ub[a]=c=V.getUniformLocation(b,b.mc[a]+(0<c?"["+c+"]":"")));return c}T(1282)}var X=[],Y=[];function Cb(a){var b=zb(a)+1,c=Db(b);O(a,c,b);return c}
for(var V,Eb=new Float32Array(288),Z=0;288>Z;++Z)X[Z]=Eb.subarray(0,Z+1);var Fb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Fb.subarray(0,Z+1);
var Mb={$:function(){return 0},db:function(){},fb:function(){return 0},bb:function(){},gb:function(){},cb:function(){},q:function(){z("")},F:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},J:function(a,b,c){a=N(a);if(!a)return-4;a=Ua(a);E[b>>3]=a.width;E[c>>3]=a.height;return 0},o:()=>performance.now(),hb:function(a,b,c){A.copyWithin(a,b,b+c)},Wa:function(a,b){function c(d){F.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:function(){z("OOM")},K:function(a,
b,c,d){return Va(a,b,c,d,12,"blur")},D:function(a,b,c){a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},L:function(a,b,c,d){return Va(a,b,c,d,13,"focus")},U:function(a,b,c,d){return Wa(a,b,c,d,2,"keydown")},S:function(a,b,c,d){return Wa(a,b,c,d,1,"keypress")},T:function(a,b,c,d){return Wa(a,b,c,d,3,"keyup")},da:function(a,b,c,d){return Q(a,b,c,d,5,"mousedown")},X:function(a,b,c,d){return Q(a,b,c,d,33,"mouseenter")},W:function(a,b,c,d){return Q(a,b,c,d,34,"mouseleave")},Y:function(a,b,c,d){return Q(a,
b,c,d,8,"mousemove")},aa:function(a,b,c,d){return Q(a,b,c,d,6,"mouseup")},N:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Sb||document.body.bc||document.body.ac))return-1;a=N(a);if(!a)return-4;Ya(a,b,c,d,"mozpointerlockchange");Ya(a,b,c,d,"webkitpointerlockchange");Ya(a,b,c,d,"mspointerlockchange");return Ya(a,b,c,d,"pointerlockchange")},M:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Sb||document.body.bc||document.body.ac))return-1;
a=N(a);if(!a)return-4;Za(a,b,c,d,"mozpointerlockerror");Za(a,b,c,d,"webkitpointerlockerror");Za(a,b,c,d,"mspointerlockerror");return Za(a,b,c,d,"pointerlockerror")},Qa:function(a,b,c,d){return $a(a,b,c,d)},O:function(a,b,c,d){return ab(a,b,c,d,25,"touchcancel")},P:function(a,b,c,d){return ab(a,b,c,d,23,"touchend")},Q:function(a,b,c,d){return ab(a,b,c,d,24,"touchmove")},R:function(a,b,c,d){return ab(a,b,c,d,22,"touchstart")},I:function(a,b,c,d){tb(a,b,c,d,31,"webglcontextlost");return 0},H:function(a,
b,c,d){tb(a,b,c,d,32,"webglcontextrestored");return 0},V:function(a,b,c,d){return(a=N(a))?"undefined"!=typeof a.onwheel?ub(a,b,c,d):-1:-4},y:function(a,b){b>>=2;b={alpha:!!B[b],depth:!!B[b+1],stencil:!!B[b+2],antialias:!!B[b+3],premultipliedAlpha:!!B[b+4],preserveDrawingBuffer:!!B[b+5],powerPreference:vb[B[b+6]],failIfMajorPerformanceCaveat:!!B[b+7],sc:B[b+8],yc:B[b+9],cc:B[b+10],qc:B[b+11],Ac:B[b+12],Bc:B[b+13]};a=N(a);return!a||b.qc?0:pb(a,b)},xb:function(a,b){a=kb[a];b=J(b);b.startsWith("GL_")&&
(b=b.substr(3));"ANGLE_instanced_arrays"==b&&bb(V);"OES_vertex_array_object"==b&&cb(V);"WEBGL_draw_buffers"==b&&db(V);"WEBGL_multi_draw"==b&&eb(V);return!!a.Zb.getExtension(b)},wa:function(a){a>>=2;for(var b=0;14>b;++b)B[a+b]=0;B[a]=B[a+1]=B[a+3]=B[a+4]=B[a+8]=B[a+10]=1},na:function(a){sb=kb[a];f.vc=V=sb&&sb.Zb;return!a||V?0:-5},Z:function(){return 52},eb:function(){return 52},$a:function(){return 70},_:function(a,b,c,d){for(var e=0,k=0;k<c;k++){var g=C[b>>2],m=C[b+4>>2];b+=8;for(var n=0;n<m;n++){var r=
A[g+n],q=wb[a];0===r||10===r?((1===a?fa:x)(Aa(q,0)),q.length=0):q.push(r)}e+=m}C[d>>2]=e;return 0},p:function(a){V.activeTexture(a)},C:function(a,b){V.attachShader(R[a],S[b])},b:function(a,b){V.bindBuffer(a,gb[b])},z:function(a,b){V.bindFramebuffer(a,hb[b])},Ga:function(a,b){V.bindRenderbuffer(a,ib[b])},f:function(a,b){V.bindTexture(a,jb[b])},u:function(a,b,c,d){V.blendColor(a,b,c,d)},v:function(a,b){V.blendEquationSeparate(a,b)},w:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Ia:function(a,b,c,
d){V.bufferData(a,c?A.subarray(c,c+b):b,d)},E:function(a,b,c,d){V.bufferSubData(a,b,A.subarray(d,d+c))},qa:function(a){V.clear(a)},ta:function(a,b,c,d){V.clearColor(a,b,c,d)},sa:function(a){V.clearDepth(a)},ra:function(a){V.clearStencil(a)},g:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},jb:function(a){V.compileShader(S[a])},Da:function(a,b,c,d,e,k,g,m){V.compressedTexImage2D(a,b,c,d,e,k,m?A.subarray(m,m+g):null)},Ba:function(){var a=ob(R),b=V.createProgram();b.name=a;b.Yb=b.Wb=b.Xb=0;b.$b=1;R[a]=
b;return a},lb:function(a){var b=ob(S);S[b]=V.createShader(a);return b},t:function(a){V.cullFace(a)},Ka:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=gb[d];e&&(V.deleteBuffer(e),e.name=0,gb[d]=null)}},m:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=hb[d];e&&(V.deleteFramebuffer(e),e.name=0,hb[d]=null)}},G:function(a){if(a){var b=R[a];b?(V.deleteProgram(b),b.name=0,R[a]=null):T(1281)}},ca:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=ib[d];e&&(V.deleteRenderbuffer(e),e.name=
0,ib[d]=null)}},l:function(a){if(a){var b=S[a];b?(V.deleteShader(b),S[a]=null):T(1281)}},ob:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=jb[d];e&&(V.deleteTexture(e),e.name=0,jb[d]=null)}},j:function(a){V.depthFunc(a)},k:function(a){V.depthMask(!!a)},a:function(a){V.disable(a)},r:function(a){V.disableVertexAttribArray(a)},pb:function(a,b,c){V.drawArrays(a,b,c)},qb:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},rb:function(a,b,c,d){V.drawElements(a,b,c,d)},sb:function(a,b,c,d,e){V.drawElementsInstanced(a,
b,c,d,e)},d:function(a){V.enable(a)},ka:function(a){V.enableVertexAttribArray(a)},s:function(a){V.frontFace(a)},Ja:function(a,b){xb(a,b,"createBuffer",gb)},Ha:function(a,b){xb(a,b,"createRenderbuffer",ib)},Ea:function(a,b){xb(a,b,"createTexture",jb)},xa:function(a,b){return V.getAttribLocation(R[a],J(b))},c:function(a,b){yb(a,b)},za:function(a,b,c,d){a=V.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(B[c>>2]=b)},B:function(a,b,c){if(c)if(a>=fb)T(1281);else if(a=R[a],
35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.Yb)for(b=0;b<V.getProgramParameter(a,35718);++b)a.Yb=Math.max(a.Yb,V.getActiveUniform(a,b).name.length+1);B[c>>2]=a.Yb}else if(35722==b){if(!a.Wb)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Wb=Math.max(a.Wb,V.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.Wb}else if(35381==b){if(!a.Xb)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Xb=Math.max(a.Xb,V.getActiveUniformBlockName(a,b).length+
1);B[c>>2]=a.Xb}else B[c>>2]=V.getProgramParameter(a,b);else T(1281)},ib:function(a,b,c,d){a=V.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(B[c>>2]=b)},ba:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(S[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=V.getShaderParameter(S[a],b):T(1281)},Ma:function(a){var b=lb[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+
d}));b=Ab(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||T(1280);b=b&&Ab(b);break;case 7938:b=Ab("OpenGL ES 2.0 ("+V.getParameter(7938)+")");break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ab(b);break;default:T(1280)}lb[a]=b}return b},A:function(a,b){b=J(b);if(a=R[a]){var c=a,d=c.Ub,e=c.nc,k;if(!d)for(c.Ub=d={},c.mc={},k=0;k<V.getProgramParameter(c,
35718);++k){var g=V.getActiveUniform(c,k);var m=g.name;g=g.size;var n=Bb(m);n=0<n?m.slice(0,n):m;var r=c.$b;c.$b+=g;e[n]=[g,r];for(m=0;m<g;++m)d[r]=m,c.mc[r++]=n}c=a.Ub;d=0;e=b;k=Bb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.nc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else T(1281);return-1},Aa:function(a){a=R[a];V.linkProgram(a);a.Ub=0;a.nc={}},La:function(a,b){3317==a&&(mb=b);V.pixelStorei(a,b)},x:function(a,b){V.polygonOffset(a,b)},Fa:function(a,b,
c,d){V.renderbufferStorage(a,b,c,d)},ua:function(a,b,c,d){V.scissor(a,b,c,d)},kb:function(a,b,c,d){for(var e="",k=0;k<b;++k){var g=d?B[d+4*k>>2]:-1;e+=J(B[c+4*k>>2],0>g?void 0:g)}V.shaderSource(S[a],e)},nb:function(a,b,c){V.stencilFunc(a,b,c)},pa:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},i:function(a){V.stencilMask(a)},mb:function(a,b,c){V.stencilOp(a,b,c)},oa:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Ca:function(a,b,c,d,e,k,g,m,n){var r=V,q=r.texImage2D;if(n){var p=m-5120;p=1==p?A:
4==p?B:6==p?D:5==p||28922==p?C:ka;var M=31-Math.clz32(p.BYTES_PER_ELEMENT),U=mb;n=p.subarray(n>>M,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<M)+U-1&-U)>>M)}else n=null;q.call(r,a,b,c,d,e,k,g,m,n)},e:function(a,b,c){V.texParameteri(a,b,c)},ja:function(a,b,c){if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=D[c+4*e>>2];else d=D.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)},ya:function(a,b){V.uniform1i(W(a),b)},fa:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>
2,c+4*b>>2);V.uniform1iv(W(a),d)},ia:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2];else d=D.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)},wb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)},ha:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2];else d=D.subarray(c>>2,c+12*
b>>2);V.uniform3fv(W(a),d)},vb:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)},ga:function(a,b,c){if(72>=b){var d=X[4*b-1],e=D;c>>=2;for(var k=0;k<4*b;k+=4){var g=c+k;d[k]=e[g];d[k+1]=e[g+1];d[k+2]=e[g+2];d[k+3]=e[g+3]}}else d=D.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)},ub:function(a,b,c){if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+
4)>>2],d[e+2]=B[c+(4*e+8)>>2],d[e+3]=B[c+(4*e+12)>>2];else d=B.subarray(c>>2,c+16*b>>2);V.uniform4iv(W(a),d)},tb:function(a,b,c,d){if(18>=b){var e=X[16*b-1],k=D;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=k[m];e[g+1]=k[m+1];e[g+2]=k[m+2];e[g+3]=k[m+3];e[g+4]=k[m+4];e[g+5]=k[m+5];e[g+6]=k[m+6];e[g+7]=k[m+7];e[g+8]=k[m+8];e[g+9]=k[m+9];e[g+10]=k[m+10];e[g+11]=k[m+11];e[g+12]=k[m+12];e[g+13]=k[m+13];e[g+14]=k[m+14];e[g+15]=k[m+15]}}else e=D.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(W(a),!!c,e)},
h:function(a){a=R[a];V.useProgram(a);V.oc=a},la:function(a,b){V.vertexAttribDivisor(a,b)},ma:function(a,b,c,d,e,k){V.vertexAttribPointer(a,b,c,!!d,e,k)},va:function(a,b,c,d){V.viewport(a,b,c,d)},Za:function(){f.fc=a=>{0!=Gb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.fc)},Ya:function(){f.lc=a=>{const b=a.clipboardData.getData("text");Ba(()=>{const c=Cb(b);Hb(c)})};window.addEventListener("paste",f.lc)},Xa:function(a){f.Cc=[];a=J(a);a=document.getElementById(a);
f.hc=b=>{b.stopPropagation();b.preventDefault()};f.ic=b=>{b.stopPropagation();b.preventDefault()};f.jc=b=>{b.stopPropagation();b.preventDefault()};f.kc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Dc=c;Ib(c.length);for(let d=0;d<c.length;d++)Ba(()=>{const e=Cb(c[d].name);Jb(d,e)});Kb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.hc,!1);a.addEventListener("dragleave",f.ic,!1);a.addEventListener("dragover",f.jc,!1);a.addEventListener("drop",f.kc,!1)},Va:function(){const a=
document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Pa:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Lb()});document.body.append(a)},Oa:function(){document.getElementById("_sokol_app_input_element").focus()},_a:function(a){a=J(a);f.Tb=document.getElementById(a);f.Tb||console.log("sokol_app.h: invalid target:"+a);f.Tb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Ta:function(){window.removeEventListener("beforeunload",f.fc)},Sa:function(){window.removeEventListener("paste",f.lc)},Ra:function(a){a=J(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.hc);a.removeEventListener("dragleave",f.ic);a.removeEventListener("dragover",f.jc);a.removeEventListener("drop",f.kc)},n:function(){f.Tb&&f.Tb.requestPointerLock&&f.Tb.requestPointerLock()},Ua:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),
k=e.createImageData(a,b);k.data.set(A.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Na:function(){document.getElementById("_sokol_app_input_element").blur()},ea:function(a,b){b=J(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;f.asm=c;ha=f.asm.yb;var d=ha.buffer;f.HEAP8=new Int8Array(d);f.HEAP16=ja=new Int16Array(d);f.HEAP32=B=new Int32Array(d);f.HEAPU8=A=new Uint8Array(d);f.HEAPU16=ka=new Uint16Array(d);f.HEAPU32=C=new Uint32Array(d);f.HEAPF32=D=new Float32Array(d);f.HEAPF64=E=new Float64Array(d);F=f.asm.Bb;ma.unshift(f.asm.zb);G--;f.monitorRunDependencies&&f.monitorRunDependencies(G);0==G&&(null!==ra&&(clearInterval(ra),ra=null),H&&(d=H,H=null,d()));return c}var b={a:Mb};G++;f.monitorRunDependencies&&
f.monitorRunDependencies(G);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return x("Module.instantiateWasm callback failed with error: "+c),!1}xa(b,function(c){a(c.instance)});return{}})();var Nb=f._main=function(){return(Nb=f._main=f.asm.Ab).apply(null,arguments)},P=f._malloc=function(){return(P=f._malloc=f.asm.Cb).apply(null,arguments)};f._free=function(){return(f._free=f.asm.Db).apply(null,arguments)};
var Lb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Lb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Eb).apply(null,arguments)},Hb=f.__sapp_emsc_onpaste=function(){return(Hb=f.__sapp_emsc_onpaste=f.asm.Fb).apply(null,arguments)},Gb=f.__sapp_html5_get_ask_leave_site=function(){return(Gb=f.__sapp_html5_get_ask_leave_site=f.asm.Gb).apply(null,arguments)},Ib=f.__sapp_emsc_begin_drop=function(){return(Ib=f.__sapp_emsc_begin_drop=f.asm.Hb).apply(null,arguments)},Jb=f.__sapp_emsc_drop=function(){return(Jb=
f.__sapp_emsc_drop=f.asm.Ib).apply(null,arguments)},Kb=f.__sapp_emsc_end_drop=function(){return(Kb=f.__sapp_emsc_end_drop=f.asm.Jb).apply(null,arguments)};f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Kb).apply(null,arguments)};function Ca(){return(Ca=f.asm.Lb).apply(null,arguments)}function Da(){return(Da=f.asm.Mb).apply(null,arguments)}function Db(){return(Db=f.asm.Nb).apply(null,arguments)}f.___start_em_js=42980;f.___stop_em_js=49048;var Ob;
H=function Pb(){Ob||Qb();Ob||(H=Pb)};
function Qb(){function a(){if(!Ob&&(Ob=!0,f.calledRun=!0,!ia)){ya(ma);ya(na);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Rb){var b=Nb;try{var c=b(0,0);if(!noExitRuntime){if(f.onExit)f.onExit(c);ia=!0}h(c,new w(c))}catch(d){d instanceof w||"unwind"==d||h(1,d)}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),pa.unshift(b);ya(pa)}}if(!(0<G)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)qa();
ya(la);0<G||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Rb=!0;f.noInitialRun&&(Rb=!1);Qb();
